<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BackupNormalizer</AssemblyName>
    <RootNamespace>BackupNormalizer</RootNamespace>
    <Version>0.1.0</Version>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackupNormalizer.Core\BackupNormalizer.Core.csproj" />
  </ItemGroup>

</Project>
