"""Apply bounded fixes for the pinned EF Core 10.0.12 query generator."""
from pathlib import Path
import re
import sys

directory = Path(sys.argv[1])
files = list(directory.glob("*EFInterceptors*.cs"))
if not files:
    raise FileNotFoundError("No EF query interceptors were generated.")
bindings = 0
for path in files:
    source = path.read_text()
    if "// <auto-generated />" not in source:
        raise ValueError("Expected an EF-generated source file.")
    # EF's syntax translator collects fluent SetProperty calls in reverse order,
    # while UpdateSettersBuilder stores them in call order. Extract each value
    # from the corresponding runtime position. Single-property updates are unchanged.
    source, count = re.subn(r"setters\.Expressions\[(\d+)\]",
                            lambda match: "setters.Expressions[setters.Expressions.Count - 1 - " + match[1] + "]",
                            source)
    bindings += count
    path.write_text("#nullable enable\nusing Database = global::BackupNormalizer.Database;\n" + source)
if bindings == 0:
    raise ValueError("The pinned generator's setter binding shape was not found; review tooling before publishing.")
print(f"Applied EF 10.0.12 type alias and {bindings} setter parameter bindings")
